### ISSUE TITLE
YOLOv8 License (AGPL-3.0)

### ISSUE THREAD

**Issue by datasith** [stephansturges/NANO#1]
Cool repo. Perhaps you're aware already, but assuming this work is derivative of YOLOv8, you may want to consider updating the license. YOLOv8 is licensed under AGPL-3.0, so when modifying it or including it into any other work, the resulting code (typically) must be distributed as a whole under AGPL 3.0.

- https://github.com/ultralytics/ultralytics

For the record, I'm not a fan of the license (and as a result the OG repo), but just saw your post on LinkedIn and decided to offer an unsolicited PSA.

**Comment by stephansturges** [comment]
Thanks for pointing this out, but my understanding is that this applies to the code in the ultralytics repository so I referenced in the Readme that the terms of that license in the Ultralytics repo have to be respected if the model is used with that repo by the end user, and the trained model that I am putting in the repo without any code is MIT. I think that makes sense? Also for commercial use the Ultralytics repo is actually not AGPL-3.0, they have a specific "entreprise" license for that.

**Comment by datasith** [comment]
IANAL, but that makes sense. I should've emphasized the "may want to" above, as I wasn't tracking the specifics that you seem to have covered.

And yup, painfully aware of historical nuances of YOLO models (including the enterprise distinction) dating back to its darknet origins.

Thanks for clarifying, and keep on the cool work!
